version: "3"

services:
  mysql-api-conta:
    image: mysql:5.7.21
    volumes:
      - data-mysql-api-conta:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: conta

  mysql-api-endereco:
    image: mysql:5.7.21
    volumes:
      - data-mysql-api-endereco:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: endereco

  api-conta:
    image: fernandoe/fe-conta-api:0.0.2
    ports:
      - "9000:8000"
    depends_on:
      - mysql-api-conta
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql-api-conta:3306/conta
      VERSION: 0.0.2

  api-endereco:
    build: .
    ports:
      - "9002:8000"
    volumes:
      - ./src:/app
    depends_on:
      - mysql-api-endereco
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql-api-endereco:3306/endereco
      VERSION: 0.0.2
    stdin_open: true
    tty: true

volumes:
  data-mysql-api-conta:
  data-mysql-api-endereco:
